### ISSUE TITLE
Bug in server.js?

### ISSUE THREAD

**Issue by sgrund14** [beakerbrowser/homebase#15]
Hello,

I'm trying to run homebase, but I'm getting this bug from /lib/server.js:
`TypeError: server.on is not a function`
Which is happening in this block of code:
```
// start server
  if (config.letsencrypt) {
    server = greenlockExpress.create({
      server: IS_DEBUG ? 'https://acme-staging-v02.api.letsencrypt.org/directory' : 'https://acme-v02.api.letsencrypt.org/directory',
      version: 'v02',
      debug: IS_DEBUG,
      approveDomains: approveDomains(config),
      store: require('le-store-certbot').create({
        configDir: path.join(config.directory, 'letsencrypt', 'etc'),
        workDir: path.join(config.directory, 'letsencrypt', 'var', 'lib'),
        logsDir: path.join(config.directory, 'letsencrypt', 'var', 'log')
      }),
      app: app
    });
    server.listen(config.ports.http, config.ports.https)
  } else {
    server = http.createServer(app)
    server.listen(config.ports.http)
  }
  server.on('error', function (err) {
    if (err.code === 'EACCES') {
      console.error(chalk.red(`ERROR: Failed to bind to ${chalk.bold(`port ${err.port}`)} (EACCES)
```

I've checked and server is being created successfully, but it doesn't have an on function. Any insight would be appreciated : )

This is my config file:
```
dats:
  - url: dat://1d671b7387087d527de9790520295383c1fb2fe88655bfbe78f477e87dcddd99
    domains: 
      - samgrund.com
httpMirror: true
letsencrypt:
  email: sgrund626@gmail.com
  agreeTos: true
ports:
  http: 80
  https: 443
dashboard:
  port: 8089
```
And I'm running it using `sudo homebase` (I was running a daemonized version before, but I was having trouble with it and found the issue running it directly)
