### ISSUE TITLE
greenlock skipping fronting check

### ISSUE THREAD

**Issue by slmyers** [beakerbrowser/homebase#19]
Hi, for some reason I am unable to integrate with letsencrypt. I can run the server without letsencrypt, using http only and on port 80. I think there is a problem in my config file. Here is my config file

 ```yml
directory: ~/.homebase
httpMirror: true
ports:
  http: 80
  https: 403
letsencrypt:
        email: slmyers@ualberta.ca
        agreeTos: true
dats:
  - url: dat://63df89db2d373b5575632b386c2fd651fc686ac54445ce450028e8151f07780a
    domains: slmyers.info
```

here is my output

```
slmyers_dev@homebase-1:~$ export NODE_ENV=production
slmyers_dev@homebase-1:~$ homebase

== Homebase 2.0.3 ==

 ▶ Directory:    /home/slmyers_dev/.homebase
 ▶ Ports:        80 (HTTP) 403 (HTTPS)
 ▶ HTTP mirror:  ✔ enabled
 ▶ Lets Encrypt: ✔ enabled
 ▶ Dashboard:    ✖ disabled
 ▶ WebAPI:       ✖ disabled 

Serving
  dat://63df89db2d373b5575632b386c2fd651fc686ac54445ce450028e8151f07780a
  at slmyers.info

/* quite a long pause here */

[greenlock] WARN: no string for req.socket.servername, skipping fronting check for 'slmyers.info'
```

I get `ERR_CONNECTION_REFUSED` when connecting via `https` or `http`.
Can anyone please help me? Thanks.
