### ISSUE TITLE
Homebase command working, Homebase command via pm2 is not working

### ISSUE THREAD

**Issue by edouerd** [beakerbrowser/homebase#22]
Hello!

When I attempt to run `homebase` by itself, my web pages via .dat are hosted fine, and show up when navigated to:

<img width="1473" alt="screen shot 2018-10-02 at 08 12 11" src="https://user-images.githubusercontent.com/1195363/46347957-52c72680-c61b-11e8-85e5-ddebd0d9cc7b.png">

When I attempt to run `homebase` via pm2 as a daemon, I receive an error state when I type `pm2 show homebase`:

<img width="1473" alt="screen shot 2018-10-02 at 08 13 03" src="https://user-images.githubusercontent.com/1195363/46347962-578bda80-c61b-11e8-9672-afe7478a4b31.png">

I dug into the error file and saw the following, which is weird because when I navigate to the indicated url, the domain part it specifies is deprecated:

<img width="1473" alt="screen shot 2018-10-02 at 08 14 03" src="https://user-images.githubusercontent.com/1195363/46347996-768a6c80-c61b-11e8-90b3-7355858b9515.png">

This is my current homebase.yml configuration:

```
directory: ~/.homebase # where your data will be stored
httpMirror: true       # enables http mirrors of the dats
ports:
  http: 80             # HTTP port for redirects or non-SSL serving
  https: 443           # HTTPS port for serving mirrored content & DNS data
letsencrypt:          # set to false to disable lets-encrypt
  email: mail@edouard.us
  agreeTos: true       # you must agree to the LE terms (set to true)
dashboard:             # set to false to disable
  port: 8089           # port for accessing the metrics dashboard

# enable publishing to homebase from Beaker and the Dat CLI
webapi: false                # set to false to disable

# enter your pinned dats here
dats:
  - url: dat://88cc4007d96d02dac3d92d209c70e43b1440fde9c1749382b3e17fcc972359a6/
    domains:
      - mornings.co
  - url: dat://1930ff236d0ca1f6cb3b99268b97befafd11198186dc353539329c58e66882fd/
    domains:
      - maybe.clothing
  - url: dat://0f01013e65929d99c88bc83020690f2199b704faf83a17d9195c7cb4e06b18e1/
    domains:
      - edouard.mornings.co
  - url: dat://0f01013e65929d99c88bc83020690f2199b704faf83a17d9195c7cb4e06b18e1/
    domains:
      - edouard.us
  - url: dat://18d6b180716942b54936ece9b3f3c718762189faa554bf49a6c1053182dc722f/
    domains:
      - openses.am
```
