### ISSUE TITLE
Deploying a nodejs app using homebase

### ISSUE THREAD

**Issue by whiteyhat** [beakerbrowser/homebase#40]
Hi! I have not understood very well this process. Normally in a server using Nginx I would create a server block and then a proxy that points the `localhost:port` to an IP from the server.

## Homebase config
Here, I have the `dat`. How would the configuration be? 
```
httpMirror: true      
ports:
  http: 80             
  https: 443           
letsencrypt:          
  email: me@email.com            
  agreeTos: true      
dashboard:            
  port: 8089           
dats:
  - url:  dat:123...456

proxies:
  - from: localhost:8080             
    to: localhost:8080             
```

## Procedures
1. Start my nginx server locally
2. Point it to the `locahost:port`
3. Point the `localhost:port` to the `dat`?
