### ISSUE TITLE
TypeError: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by decentral1se** [beakerbrowser/homebase#48]
When I run `curl -X POST -d '{"username": "foo", "password": "bar"}' https://myhomebase.foo/v1/accounts/login` and with the following .homebase.yml configuration:

```yaml
webapi:
  domain: myhomebase.foo
  username: foo
  password: bar
```

I keep receiving a HTTP 500 and seeing `TypeError: Cannot read property 'username' of undefined`.

I'm on homebase 2.0.8.
