### ISSUE TITLE
Simplify setting the base host's dat

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/homebase#7]

**Comment by webdesserts** [comment]
@pfrazee What's the current way of setting the base host's dat?

**Comment by webdesserts** [comment]
I think it would be nice if all you had to do was specify a nameless dat:

```yml
domain: webdesserts.com
dats:
  - url: dat://9f5119014f165f94221a9269f3339c5eaab406ad7221faa99dff0d903551a533
    name:
  - url: dat://4e50e4fbbc6ccf02dcb056834e335ed821f9dbaee85a7880921996e43122f355
    name: term
```

or

```yml
domain: webdesserts.com
dats:
  - url: dat://9f5119014f165f94221a9269f3339c5eaab406ad7221faa99dff0d903551a533
  - url: dat://4e50e4fbbc6ccf02dcb056834e335ed821f9dbaee85a7880921996e43122f355
    name: term
```

This is pretty much how my dns hosting provider does this as well:

<img width="388" alt="screenshot 2018-06-25 19 57 40" src="https://user-images.githubusercontent.com/916253/41883071-1265ee8e-78b2-11e8-9f59-c1b6f6d8d31e.png">

**Comment by pfrazee** [comment]
You might want to have a nameless dat for other reasons though (ie you dont want a shortname).

🤔 hmm. Okay, let's consider two changes.

 1. Moving the top-level `domain` config to be inside the `webapi` config object. This will lend some clarity about *which* domain is being set. We'd also need to add a `domain` setting to the `dashboard` object.
 2. Inside the `dats` list, rename the `otherDomains` field to just `domain`. Then `name` is optional.

Then you'll end up with configs that look like this:

```yaml
dats:
  - url: dat://9f5119014f165f94221a9269f3339c5eaab406ad7221faa99dff0d903551a533
    domain: webdesserts.com
  - url: dat://4e50e4fbbc6ccf02dcb056834e335ed821f9dbaee85a7880921996e43122f355
    domain: term.webdesserts.com

webapi: # if you want it
  domain: webdesserts.com
```
